[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#1A73E8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
